In [2]:
import os
os.chdir(r"C:\Users\Randall\OneDrive\Documents\STATA\mus")

In [15]:
import numpy as np
import pandas as pd
from scipy.optimize import minimize
from scipy.stats import poisson

data = pd.read_stata('mus10data.dta')
data = data[data['year02']==1]
data['cons'] = 1
y = data['docvis'].values
X = data[['private', 'chronic', 'female', 'income', 'cons']].values

def loglikelihood(b):
    μ = np.exp(X @ b)
    return -poisson.logpmf(y, μ).sum()

b = np.array([0.0, 0.0, 0.0, 0.0, 1.0])
res = minimize(loglikelihood, b)

In [20]:
X.mean(axis=0)

array([ 0.78535811,  0.32638259,  0.47189483, 34.34017794,  1.        ])

In [32]:
inc = X.mean(axis=0)[3]

Xforecast = np.array(
    [[0, 0, 0, inc, 1], [0, 0, 1, inc, 1],[0, 1, 0, inc, 1],[0, 1, 1, inc, 1],
    [1, 0, 0, inc, 1], [1, 0, 1, inc, 1],[1, 1, 0, inc, 1],[1, 1, 1, inc, 1]])

Xforecast2 = Xforecast.copy()
Xforecast2[:,3] *= 2

print(np.exp(Xforecast @ res.x).round(1).reshape([2,-1]))
print(np.exp(Xforecast2 @ res.x).round(1).reshape([2,-1]))

[[0.9 1.5 2.7 4.4]
 [2.  3.3 5.9 9.7]]
[[ 1.   1.7  3.   4.9]
 [ 2.3  3.7  6.7 11. ]]
